### ISSUE TITLE
Support other LLMs than OpenAI

### ISSUE THREAD

**Issue by kaikreuzer** [eclipse-lmos/lmos-router#30]
The lmos-router implementation currently only supports OpenAI as a model provider.
Arc in comparison has multiple client options, such as Ollama or even more general LangChain4j.

It would be good if the router would also support such options.
Would it make sense to move certain client classes from arc to something like lmos-commons, so that it does not have to be replicated for the router?

**Comment by RobWin** [comment]
Indeed. For this LMOS Kernel is used at DT, but I think we can migrate the "low-level" access of LLMs to Langchain4j and maybe add a slim layer out top of it.

**Comment by xmxnt** [comment]
Langchain4j sounds like a good default for model provider. We can implement this now and later move to lmos-commons when available. What do you think?

**Comment by kaikreuzer** [comment]
Sounds fine to me.
